version: "3.8"

services:
    # image project
    motorez:
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/arm64/v8
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

        networks:
            - mz_network
        extra_hosts:
            - "host.docker.internal:host-gateway"
            
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8986:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - mz_network

    mysql:
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3339:3306"
        networks:
            - mz_network

networks:
    mz_network:
        external: true