version: "3.8"

services:
    # image project
    motorez:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

        networks:
            - mz_network